package net.vampirestudios.packwright.data.registry.dialog;

import com.mojang.datafixers.util.Either;
import com.mojang.datafixers.util.Pair;
import com.mojang.serialization.Codec;
import com.mojang.serialization.DataResult;
import com.mojang.serialization.DynamicOps;
import com.mojang.serialization.MapLike;
import com.mojang.serialization.codecs.RecordCodecBuilder;
import net.minecraft.resources.Identifier;
import net.minecraft.util.StringRepresentable;

import java.util.List;
import java.util.Optional;

/**
 * A dialog in the {@code dialog} registry (screen shown to the player via {@code /dialog show}
 * or a click action). Vanilla defines five dialog types, one record per {@code permits} entry:
 * {@link NoticeDialog}, {@link ConfirmationDialog}, {@link ServerLinksDialog},
 * {@link DialogListDialog} and {@link MultiActionDialog}.
 *
 * <pre>{@code
 * Dialog.notice("Welcome", "Continue")
 *     .plainMessage("This dialog was generated by Packwright.")
 *     .input(Input.text("name", "Name"))
 * }</pre>
 */
public sealed interface Dialog permits NoticeDialog, ConfirmationDialog, ServerLinksDialog, DialogListDialog, MultiActionDialog {
	Codec<Dialog> CODEC = new Codec<>() {
		@Override
		public <T> DataResult<Pair<Dialog, T>> decode(DynamicOps<T> ops, T input) {
			return ops.getMap(input).flatMap(map -> switch (normalizeType(string(map, ops, "type", ""))) {
				case "notice" -> NoticeDialog.CODEC.codec().decode(ops, input).map(pair -> pair.mapFirst(x -> x));
				case "confirmation" -> ConfirmationDialog.CODEC.codec().decode(ops, input).map(pair -> pair.mapFirst(x -> x));
				case "server_links" -> ServerLinksDialog.CODEC.codec().decode(ops, input).map(pair -> pair.mapFirst(x -> x));
				case "dialog_list" -> DialogListDialog.CODEC.codec().decode(ops, input).map(pair -> pair.mapFirst(x -> x));
				case "multi_action" -> MultiActionDialog.CODEC.codec().decode(ops, input).map(pair -> pair.mapFirst(x -> x));
				default -> DataResult.error(() -> "Unsupported dialog type");
			});
		}

		@Override
		public <T> DataResult<T> encode(Dialog input, DynamicOps<T> ops, T prefix) {
			if (input instanceof NoticeDialog d) return NoticeDialog.CODEC.codec().encode(d, ops, prefix);
			if (input instanceof ConfirmationDialog d) return ConfirmationDialog.CODEC.codec().encode(d, ops, prefix);
			if (input instanceof ServerLinksDialog d) return ServerLinksDialog.CODEC.codec().encode(d, ops, prefix);
			if (input instanceof DialogListDialog d) return DialogListDialog.CODEC.codec().encode(d, ops, prefix);
			if (input instanceof MultiActionDialog d) return MultiActionDialog.CODEC.codec().encode(d, ops, prefix);
			return DataResult.error(() -> "Unsupported dialog: " + input.getClass().getSimpleName());
		}
	};

	CommonDialogData common();

	// ---------- factories ----------

	static NoticeDialog notice(String title, String actionLabel) {
		return new NoticeDialog(CommonDialogData.of(title), Optional.of(Button.button(actionLabel)));
	}

	static ConfirmationDialog confirmation(String title, String yesLabel, String noLabel) {
		return new ConfirmationDialog(CommonDialogData.of(title), Button.button(yesLabel), Button.button(noLabel));
	}

	static ServerLinksDialog serverLinks(String title) {
		return new ServerLinksDialog(CommonDialogData.of(title), Optional.empty(), 2, 150);
	}

	static DialogListDialog dialogList(String title, Reference... dialogs) {
		return new DialogListDialog(CommonDialogData.of(title), List.of(dialogs), Optional.empty(), 2, 150);
	}

	static MultiActionDialog multiAction(String title, Button... actions) {
		return new MultiActionDialog(CommonDialogData.of(title), List.of(actions), Optional.empty(), 2);
	}

	/** {@code close}/{@code none}/{@code wait_for_response} — what happens to the dialog after a button is clicked */
	enum AfterAction implements StringRepresentable {
		CLOSE("close"),
		NONE("none"),
		WAIT_FOR_RESPONSE("wait_for_response");

		public static final Codec<AfterAction> CODEC = StringRepresentable.fromEnum(AfterAction::values);
		private final String name;
		AfterAction(String name) { this.name = name; }
		@Override public String getSerializedName() { return name; }

		public boolean willUnpause() { return this == CLOSE || this == WAIT_FOR_RESPONSE; }
	}

	/** a clickable button: label + optional tooltip/width/action (vanilla's {@code CommonButtonData} + {@code ActionButton} merged flat) */
	record Button(String label, Optional<String> tooltip, int width, Optional<Action> action) {
		public static final Codec<Button> CODEC = RecordCodecBuilder.create(i -> i.group(
				Codec.STRING.fieldOf("label").forGetter(Button::label),
				Codec.STRING.optionalFieldOf("tooltip").forGetter(Button::tooltip),
				Codec.INT.fieldOf("width").orElse(150).forGetter(Button::width),
				Action.CODEC.optionalFieldOf("action").forGetter(Button::action)
		).apply(i, Button::new));

		public static Button button(String label) { return new Button(label, Optional.empty(), 150, Optional.empty()); }
		public Button tooltip(String tooltip) { return new Button(label, Optional.of(tooltip), width, action); }
		public Button width(int width) { return new Button(label, tooltip, width, action); }
		public Button action(Action action) { return new Button(label, tooltip, width, Optional.of(action)); }
	}

	/** a reference to another dialog: either an id pointing at a registered dialog, or an inline definition */
	record Reference(Identifier id, Dialog inline) {
		public static final Codec<Reference> CODEC = Codec.either(Identifier.CODEC, Dialog.CODEC).xmap(
				either -> either.map(Reference::id, Reference::inline),
				reference -> reference.id != null ? Either.left(reference.id) : Either.right(reference.inline)
		);

		public static Reference id(Identifier id) { return new Reference(id, null); }
		public static Reference id(String id) { return id(Identifier.tryParse(id)); }
		public static Reference inline(Dialog dialog) { return new Reference(null, dialog); }
	}

	private static String normalizeType(String type) {
		int separator = type.indexOf(':');
		return separator >= 0 ? type.substring(separator + 1) : type;
	}

	private static <T> String string(MapLike<T> map, DynamicOps<T> ops, String key, String fallback) {
		T value = map.get(key);
		return value == null ? fallback : ops.getStringValue(value).result().orElse(fallback);
	}
}
